### ISSUE TITLE
deprecated call to collection.Iterable

### ISSUE THREAD

**Issue by lawsonlewis1** [jiffyclub/ipythonblocks#41]
Call to collections.Iterable is deprecated for python versions 3.10 + , consider upgrading to collections.abc.Iterable

Example:
-> 572 elif isinstance(value, (collections.Iterable, Block)):

**Comment by bonimart** [comment]
Should already be fixed by https://github.com/jiffyclub/ipythonblocks/commit/58ea7aac3cef6503e3cf72960e05cf8a5cb08526, however the fix isn't released yet.

**Comment by jiffyclub** [comment]
I released version 1.9.1, which will hopefully fix this.
